---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    -
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: nginx
    tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        track: stable
    spec:
      containers:
        -
          image: "registry.ng.bluemix.net/alexanderallen/nginx:latest"
          lifecycle:
            preStop:
              exec:
                command:
                  - /usr/sbin/nginx
                  - "-s"
                  - quit
          name: nginx
          imagePullPolicy: IfNotPresent
          ports:
            -
              containerPort: 8080
              name: http
          volumeMounts:
            -
              mountPath: /www
              name: sites-local-storage

            # Mount "hot" file from host for development.
            # The "mountPath" is the target location.
            - mountPath: /etc/nginx/conf.d/fastcgi.conf
              name: sites-local-storage
              # The "sub-path" param is the source location.
              # The source sub path is located in the /www volume (~/Sites on the host).
              subPath: nginx-php-container-cluster/k8-minikube/build/nginx/fastcgi.conf

            # Development.
            - mountPath: /etc/nginx/nginx.conf
              name: sites-local-storage
              subPath: nginx-php-container-cluster/k8-minikube/build/nginx/nginx.conf

            # Development.
            - mountPath: /etc/nginx/fastcgi_params
              name: sites-local-storage
              subPath: nginx-php-container-cluster/k8-minikube/build/nginx/fastcgi_params

            - mountPath: /www-data
              name: shared-volume
              readOnly: false

          env:
            -
              name: WEB_ROOT
              value: /www

        # PHP-CLI sidecar container.
        - image: "registry.ng.bluemix.net/alexanderallen/php-cli:latest"
          name: php-cli-sidecar
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /www-data
              name: shared-volume
              readOnly: false

      imagePullSecrets:
        -
          name: image-pull

      volumes:
        -
          name: sites-local-storage
          persistentVolumeClaim:
            claimName: local-sites-claim

        # Ephemeral tmpfs (ramdisk) volume for sharing code.
        - name: shared-volume
          emptyDir: {}
